meta_product_name: "1streamer"
meta_title: "1streamer - All your streaming platforms in one place"
meta_description: "The easy way to search all your streaming platforms in one app.  Search through all the movies and TV shows, and then go directly to the platform it's on."
meta_image: "1Streamer.png" # should exist in `app/assets/images/`
