meta_product_name: "1streamer"
meta_title: "1streamer - All your streaming platforms in one place"
meta_description: "1streamer aggregates all the streaming titles - with the universal search it's easy to find the title your are looking for."
meta_image: "cover.png" # should exist in `app/assets/images/`
